### ISSUE TITLE
Handle non-SRT packets

### ISSUE THREAD

**Issue by maxsharabayko** [mbakholdina/lib-tcpdump-processing#1]
When network capture has nonSRT packets, they are extracted to CSV, SRT related fields are NA.

* srt.iscontrol
* srt.type
* srt.seqno
* ...

This causes errors when loading CSV in `extract_srt_packets()` (NA can't be converted to integer)
```
packets = pd.read_csv(filepath, sep=';', dtype=columns_types)
```

Sample capture file for tests:
[win-cent-sendfile-busy-snd-nonsrtmixed.zip](https://github.com/mbakholdina/lib-tcpdump-processing/files/3819716/win-cent-sendfile-busy-snd-nonsrtmixed.zip)

Possible solutions:
* Replace int fields with float
* Add filter when extracting to CSV with tshark: `-f "srt"`

**Comment by mbakholdina** [comment]
The issue has been fixed with [the commit 4414f58598fb5caaae9302821e65721001b30847](https://github.com/mbakholdina/lib-tcpdump-processing/commit/4414f58598fb5caaae9302821e65721001b30847). The use of filter `-f "srt"` is not correct because I am going to add the opportunity of parsing UDT and other protocols packets for the purpose of future performance evaluation. Function `convert_to_csv` (`convert.py`) is intended to convert `.pcapng` to `.csv` as is without any additional processing.
