### ISSUE TITLE
Unable to pip install from git (fix documentation)

### ISSUE THREAD

**Issue by ghost** [mbakholdina/lib-tcpdump-processing#29]
Hi!

According to documentation one should be able to `pip install` via git URL, but following instruction installation fails due to missing git tag:

```
$ pip install 'git+https://github.com/mbakholdina/lib-tcpdump-processing.git@v0.1#egg=tcpdump_processing'
...
Collecting tcpdump_processing
  Cloning https://github.com/mbakholdina/lib-tcpdump-processing.git (to revision v0.1) to /tmp/pip-install-s645967c/tcpdump-processing
  WARNING: Did not find branch or tag 'v0.1', assuming revision or ref.
ERROR: Command errored out with exit status 1: git checkout -q v0.1 Check the logs for full command output.
```

**Comment by mbakholdina** [comment]
Hi @jurisbu, the reason you were not able to install the library was in the absence of tag v0.1. In the documentation, it's just an example of how the library can be installed from the other project. I used to work directly with master or a particular branch, e.g.,
```
git+https://github.com/mbakholdina/lib-tcpdump-processing.git@master#egg=tcpdump_processing
```

For your convenience, I've created a [tag v0.1](https://github.com/mbakholdina/lib-tcpdump-processing/releases/tag/v0.1) so that the specified in your comment command should work for now. Please note that the tag is pointing to [this commit](https://github.com/mbakholdina/lib-tcpdump-processing/commit/1aa55dff2defb1102210e38a064beeb733ea68d5) dated December 13, 2019. The current version is still in progress.

**Comment by ghost** [comment]
OK, thank you! That clears it up!
