### ISSUE TITLE
results of three scripts

### ISSUE THREAD

**Issue by SeanOntheWay** [mbakholdina/lib-tcpdump-processing#42]
Thank you for the tool!!!
But when I ran _`venv/bin/extract-packets [OPTIONS] PATH`_,`venv/bin/get-traffic-stats [OPTIONS] PATH` and `venv/bin/plot-snd-timing [OPTIONS] PATH`,they gave me the same` .csv file` in the end.Here is the result(part of it):
![image](https://user-images.githubusercontent.com/126575203/223445552-4d3510c0-7e58-41a3-b620-72343d5b1a83.png)
And they gave me the same error report:
![image](https://user-images.githubusercontent.com/126575203/223446185-b3537dd3-44b3-4b29-b3c9-7dc610d59578.png)
I really want to get the other two results of the scripts...what can I do

**Comment by mbakholdina** [comment]
Hi @SeanOntheWay,

The output `.csv` file you get would be the same, because it's just a processing and parsing of the `tshark` dump file into `.csv` format. 

If you would like to extract packets of a particular type, e.g., DATA packets only, use the 
```
--type [srt|data|control|probing|umsg_handshake|umsg_ack]
```
option of the `extract-packets` script as described [here](https://github.com/mbakholdina/lib-tcpdump-processing#extract-packets). In addition to the main `.csv` file with all the packets, you would also get another one with packets of interest only.

`get-traffic-stats` script doesn't produce any other files, the output report would be printed in the terminal.
